# Generated by Django 4.1.7 on 2023-04-03 05:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipe_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_favourite_recipe_alter_favourite_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Favorite',
        ),
    ]
