# Generated by Django 4.1.7 on 2023-03-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_favourite_favourite_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
