# Generated by Django 4.1.7 on 2023-04-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_shoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['id'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['id'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['id'], 'verbose_name': 'Покупки', 'verbose_name_plural': 'Покупки'},
        ),
    ]
